// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMKi4B6lTRgB2VysDtbGQqdZLoEM-ph0M',
    appId: '1:738908491831:web:27fcac79733adfa3712fb2',
    messagingSenderId: '738908491831',
    projectId: 'managerpassword-734ca',
    authDomain: 'managerpassword-734ca.firebaseapp.com',
    storageBucket: 'managerpassword-734ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF4HEP8UDFZK9TbR3BJli4qZUyG4tBAnU',
    appId: '1:738908491831:android:e0a9b0463b11bf91712fb2',
    messagingSenderId: '738908491831',
    projectId: 'managerpassword-734ca',
    storageBucket: 'managerpassword-734ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB50T_vctaMGYjJDiEofSadiyJz6FtpRVA',
    appId: '1:738908491831:ios:79936156f7ca8bcf712fb2',
    messagingSenderId: '738908491831',
    projectId: 'managerpassword-734ca',
    storageBucket: 'managerpassword-734ca.appspot.com',
    iosClientId: '738908491831-fgh6c0hue84u56b5vi0f4srj5rh5ggrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPractice',
  );
}
